version: "3.8"
services:
  next-app:
    image: ghcr.io/pavan731/next-app:latest
    env_file:
      - /home/ubuntu/.env.local
    ports:
      - "80:3000"
    restart: unless-stopped
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend

volumes:
  grafana-storage:

networks:
  backend:
