version: '3.9'

services:
  chatbot:
    container_name: my-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
