global:
  scrape_interval: 15s  # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate alerting rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape metrics from Next.js app (if it exposes metrics)
  - job_name: 'next-app'
    static_configs:
      - targets: ['next-app:3000']
